# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6877c7f11f493f038f1c267b3414e48462e0a2628924db4525c9bd11b2d4efeae2ee4d8294e3208e1b883cd4fdac93f09e2a75813e0e8a2d1a091621b0b38e

test:
  secret_key_base: eeb0244771e96ce5a9d30223f754c49c8ce720e99384d1db8c5767217baadde143295265c6a728d9bf460d56869811475ef7a1ba7f7434069fa88fe5ead9e247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
